[package]
name = "actionidmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.1.32"
# serde_json = "1.0.96"
time = "0.3.21"
ureq = "2.6.2"
